spring:
  application:
    name: eureka-service
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
logging:
  level:
    org.springframework: INFO
    com.instaclone: DEBUG
